# Generated by Django 3.0.3 on 2021-02-25 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busInfo.BusNo')),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busInfo.StopName')),
            ],
        ),
    ]
